corner-radius = 10;

# Исключения (чтобы не скруглять саму панель Polybar или dmenu)
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

vsync = true;
backend = "glx";
use-damage = false;

# Прозрачность активного (фокусного) окна (0.90 = 90%)
active-opacity = 1;

# Прозрачность окон на заднем плане
inactive-opacity = 1;

# Исключения (какие приложения ВСЕГДА должны быть 100% непрозрачными)
# focus-exclude = [
#   "class_g = 'Firefox'",
#   "class_g = 'Steam'",
#   "class_g = 'Vlc'"
# ];

# Включение анимаций (Синтаксис ftlabs)
animations = true;
animation-stiffness-in-out = [120, 120];
animation-smoothing = 20;

# Типы эффектов при открытии и закрытии
# Доступные пресеты: "slide-up", "slide-down", "slide-left", "slide-right", "squeeze", "zoom", "fade"
animation-for-open-window = "zoom";
animation-for-unmap-window = "squeeze";
animation-for-transient-window = "slide-down";
animation-for-prev-tag = "slide-left";
enable-fading-prev-tag = true;
animation-for-next-tag = "slide-right";
enable-fading-prev-tag = true;

unredir-if-possible = false;

wintypes:
{
  normal = { fade = true; shadow = true; animation = true; }
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dmenu = { animation = "slide-down"; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

blur-background-exclude = [
  "class_g = 'flameshot'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow-exclude = [
  "class_g = 'flameshot'"
];
