foreground            #FAF6F1
background            #252224
cursor                #C9B7B6
selection_background  #F0E9E3
selection_foreground  #252224

color0  #514E50
color8  #A8A39F
color1  #8A2A33
color9  #A1303B
color2  #922D31
color10 #A22F33
color3  #B57439
color11 #F19B4C
color4  #B57439
color5  #F19B4C
color6  #B57439
color14 #F19B4C
color7  #F0E9E3
color15 #F0E9E3
