foreground            #EBECEA
background            #282827
cursor                #939491
selection_background  #DADBD9
selection_foreground  #282827

color0  #4D4D4C
color8  #999998
color1  #23281A
color9  #23281A
color2  #323C27
color10 #323C27
color3  #383D28
color11 #383D28
color4  #3A462E
color5  #A0B77D
color6  #AFC889
color14 #AFC889
color7  #DADBD9
color15 #DADBD9
